//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCibertec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int idStock { get; set; }
        public Nullable<int> Producto_idProducto { get; set; }
        public Nullable<decimal> dblCantidad { get; set; }
        public Nullable<System.DateTime> dtFechaAct { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
